apiVersion: v1
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJhbTFoYVhKaEsyZG9YMk5wWDNONWMzUmxiVHBJT1ZNMVJqaE5XVWhUUjFWVVFWWXlNRnBUUzFrM1NqRTJSemhUUVZsRE56aEJPVVl3V1VzMVNrcFFUMGRWUjBsQ1Uxb3lVVWROVGpkSFYwMUxTVWsyIiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0K
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
type: kubernetes.io/dockerconfigjson
