apiVersion: v1
kind: Secret
metadata:
  annotations:
    tekton.dev/git-0: https://github.com
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
stringData:
  password: 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
  username: tekton
type: kubernetes.io/basic-auth
